sudo: false
language: node_js
node_js:
  - "0.12"
env:
  global:
    # Please get your own free key if you want to test yourself
    - BROWSERSTACK_USERNAME: sitepenlabs1
    - BROWSERSTACK_ACCESS_KEY: 836y5xDYPeFudz5HvZyp
cache:
  directories:
    - node_modules
script: tests/selftest.sh
